// Package reporter generates uptime digest reports from the svc history database.
package reporter

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
	"time"

	"github.com/ensignwesley/svc/internal/history"
)

// Config controls how a report is generated and delivered.
type Config struct {
	HistoryPath string
	Since       time.Duration // window for stats
	Format      string        // "table" | "markdown" | "json"
	WebhookURL  string        // if set, POST JSON report to this URL
}

// ServiceReport is the uptime summary for one service.
type ServiceReport struct {
	ID           string
	UptimePct    float64
	Incidents    int
	LastIncident *IncidentSummary
}

// IncidentSummary describes the most recent incident for a service.
type IncidentSummary struct {
	StartedAt   time.Time
	DurationSec *int64 // nil = ongoing
}

// Report is the full fleet report.
type Report struct {
	GeneratedAt time.Time
	Window      time.Duration
	Services    []ServiceReport
}

// AvgUptimePct returns the mean uptime percentage across all services.
func (r Report) AvgUptimePct() float64 {
	if len(r.Services) == 0 {
		return 100.0
	}
	var sum float64
	for _, s := range r.Services {
		sum += s.UptimePct
	}
	return sum / float64(len(r.Services))
}

// Generate opens the history database and computes uptime stats for all
// services seen within the cfg.Since window.
func Generate(cfg Config) (Report, error) {
	hdb, err := history.Open(cfg.HistoryPath)
	if err != nil {
		return Report{}, fmt.Errorf("opening history: %w", err)
	}
	defer hdb.Close()

	now := time.Now().UTC()
	sinceTS := now.Add(-cfg.Since).Unix()

	services, err := hdb.ServicesSeen(sinceTS)
	if err != nil {
		return Report{}, fmt.Errorf("querying services: %w", err)
	}

	var rows []ServiceReport
	for _, id := range services {
		pct, incidents, err := hdb.UptimePct(id, sinceTS)
		if err != nil {
			pct = 100.0
		}

		var lastInc *IncidentSummary
		incs, _ := hdb.QueryIncidents(id, sinceTS, 1)
		if len(incs) > 0 {
			lastInc = &IncidentSummary{
				StartedAt:   incs[0].StartedAt,
				DurationSec: incs[0].DurationSec,
			}
		}

		rows = append(rows, ServiceReport{
			ID:           id,
			UptimePct:    pct,
			Incidents:    incidents,
			LastIncident: lastInc,
		})
	}

	// Sort by service ID for stable output.
	sort.Slice(rows, func(i, j int) bool {
		return rows[i].ID < rows[j].ID
	})

	return Report{
		GeneratedAt: now,
		Window:      cfg.Since,
		Services:    rows,
	}, nil
}

// PrintTable writes a formatted report table to w.
func PrintTable(w io.Writer, r Report) {
	windowStr := formatDuration(r.Window)
	fmt.Fprintf(w, "Fleet Report — Last %s\n\n", windowStr)

	if len(r.Services) == 0 {
		fmt.Fprintln(w, "  No data in this window. Run 'svc check --record' to start collecting.")
		return
	}

	// Column widths.
	nameWidth := len("Service")
	for _, s := range r.Services {
		if len(s.ID) > nameWidth {
			nameWidth = len(s.ID)
		}
	}

	header := fmt.Sprintf("  %-*s  %-10s  %-10s  %s",
		nameWidth, "Service", "Uptime", "Incidents", "Last incident")
	sep := "  " + strings.Repeat("─", len(header)-2)
	fmt.Fprintln(w, header)
	fmt.Fprintln(w, sep)

	for _, s := range r.Services {
		uptimeStr := fmt.Sprintf("%.1f%%", s.UptimePct)
		lastStr := "—"
		if s.LastIncident != nil {
			lastStr = s.LastIncident.StartedAt.Format("Jan 02 15:04")
			if s.LastIncident.DurationSec != nil {
				dur := (time.Duration(*s.LastIncident.DurationSec) * time.Second).Round(time.Second)
				lastStr += " (" + dur.String() + ")"
			} else {
				lastStr += " (ongoing)"
			}
		}
		fmt.Fprintf(w, "  %-*s  %-10s  %-10d  %s\n",
			nameWidth, s.ID, uptimeStr, s.Incidents, lastStr)
	}

	fmt.Fprintf(w, "\nSummary: %d service(s), avg uptime %.1f%%\n",
		len(r.Services), r.AvgUptimePct())
}

// PrintMarkdown writes the report as a Markdown table to w.
func PrintMarkdown(w io.Writer, r Report) {
	windowStr := formatDuration(r.Window)
	fmt.Fprintf(w, "## Fleet Report — Last %s\n\n", windowStr)

	if len(r.Services) == 0 {
		fmt.Fprintln(w, "_No data in this window. Run `svc check --record` to start collecting._")
		return
	}

	fmt.Fprintln(w, "| Service | Uptime | Incidents | Last incident |")
	fmt.Fprintln(w, "|---------|--------|-----------|---------------|")

	for _, s := range r.Services {
		uptimeStr := fmt.Sprintf("%.1f%%", s.UptimePct)
		lastStr := "—"
		if s.LastIncident != nil {
			lastStr = s.LastIncident.StartedAt.Format("Jan 02 15:04")
			if s.LastIncident.DurationSec != nil {
				dur := (time.Duration(*s.LastIncident.DurationSec) * time.Second).Round(time.Second)
				lastStr += " (" + dur.String() + ")"
			} else {
				lastStr += " (ongoing)"
			}
		}
		fmt.Fprintf(w, "| %s | %s | %d | %s |\n",
			s.ID, uptimeStr, s.Incidents, lastStr)
	}

	fmt.Fprintf(w, "\n_Generated by svc on %s_\n", r.GeneratedAt.Format("2006-01-02"))
}

// webhookPayload is the JSON body POSTed to the webhook URL.
type webhookPayload struct {
	Event       string               `json:"event"`
	Window      string               `json:"window"`
	GeneratedAt string               `json:"generated_at"`
	Services    []webhookServiceRow  `json:"services"`
	Summary     webhookSummary       `json:"summary"`
}

type webhookServiceRow struct {
	ID           string          `json:"id"`
	UptimePct    float64         `json:"uptime_pct"`
	Incidents    int             `json:"incidents"`
	LastIncident *webhookIncident `json:"last_incident,omitempty"`
}

type webhookIncident struct {
	StartedAt   string  `json:"started_at"`
	DurationSec *int64  `json:"duration_sec,omitempty"`
}

type webhookSummary struct {
	TotalServices int     `json:"total_services"`
	AvgUptimePct  float64 `json:"avg_uptime_pct"`
}

// PostWebhook sends the report as a JSON POST to url. Returns an error on
// non-2xx response or transport failure.
func PostWebhook(r Report, url string) error {
	windowStr := formatDuration(r.Window)

	rows := make([]webhookServiceRow, len(r.Services))
	for i, s := range r.Services {
		row := webhookServiceRow{
			ID:        s.ID,
			UptimePct: s.UptimePct,
			Incidents: s.Incidents,
		}
		if s.LastIncident != nil {
			row.LastIncident = &webhookIncident{
				StartedAt:   s.LastIncident.StartedAt.Format(time.RFC3339),
				DurationSec: s.LastIncident.DurationSec,
			}
		}
		rows[i] = row
	}

	payload := webhookPayload{
		Event:       "report",
		Window:      windowStr,
		GeneratedAt: r.GeneratedAt.Format(time.RFC3339),
		Services:    rows,
		Summary: webhookSummary{
			TotalServices: len(r.Services),
			AvgUptimePct:  r.AvgUptimePct(),
		},
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshalling payload: %w", err)
	}

	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Post(url, "application/json", bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("posting webhook: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("webhook returned HTTP %d", resp.StatusCode)
	}
	return nil
}

// FormatDuration returns a human-friendly string like "7d" or "24h".
// Exported so main.go can use it for JSON window field.
func FormatDuration(d time.Duration) string {
	return formatDuration(d)
}

// formatDuration returns a human-friendly string like "7d" or "24h".
func formatDuration(d time.Duration) string {
	days := int(d.Hours() / 24)
	if days > 0 && d == time.Duration(days)*24*time.Hour {
		return fmt.Sprintf("%dd", days)
	}
	hours := int(d.Hours())
	if hours > 0 && d == time.Duration(hours)*time.Hour {
		return fmt.Sprintf("%dh", hours)
	}
	return d.String()
}
