package main

import (
	"fmt"
	"os"

	"github.com/ensignwesley/svc/internal/checker"
	"github.com/ensignwesley/svc/internal/manifest"
	"github.com/ensignwesley/svc/internal/output"
)

const version = "0.1.0"

const initTemplate = `# services.yaml — Service Manifest
# Generated by: svc init
#
# This file is the source of truth for your self-hosted fleet.
#
#   svc status   — check live health for every service
#   svc check    — find drift between this file and what's running
#   svc add <id> — scaffold a new entry from a running service
#

manifest:
  version: 1       # required; schema version (currently only 1 supported)
  host: localhost  # default host for health checks; override per-service via health_url

  # Units to ignore during undocumented-unit scan (svc check).
  # Use for system-managed services you deliberately exclude from the manifest.
  # ignore_units:
  #   - openclaw-gateway.service

services:

  # ── Fully specified example ──────────────────────────────────────────────────
  my-service:
    # What this service does. One sentence. Required (not enforced, but expected).
    description: "My service — describe it here"

    # Port the service listens on.
    # Derives health URL as http://{host}:{port}/health
    port: 8080

    # Override the health endpoint URL (optional).
    # Required when port is absent (e.g. static sites, external services).
    # health_url: "https://example.com/healthz"

    # systemd unit name — adds systemctl is-active check alongside HTTP poll.
    # systemd_unit: "my-service.service"

    # GitHub owner/repo for version drift detection.
    # repo: "owner/repo"

    # Currently deployed version (semver). Required for version drift detection.
    # version: "1.0.0"

    # Pin to a major version track (e.g. 22 for Node.js LTS).
    # max_major: 1

    # Link to docs or source.
    # docs: "https://github.com/owner/repo"

    # Tags for filtering: svc status --tag <tag>
    # tags:
    #   - http
    #   - security

    # Date this entry was added. Auto-set by 'svc add'.
    # added: "2026-03-16"

  # ── Minimal example (static site, no local port) ────────────────────────────
  # my-static-site:
  #   description: "Static site served by nginx"
  #   health_url: "https://example.com/"
`

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}

	cmd := os.Args[1]
	args := os.Args[2:]

	switch cmd {
	case "init":
		cmdInit(args)
	case "status":
		cmdStatus(args)
	case "check":
		cmdCheck(args)
	case "version", "--version", "-v":
		fmt.Printf("svc version %s\n", version)
	case "help", "--help", "-h":
		printUsage()
	default:
		fmt.Fprintf(os.Stderr, "svc: unknown command %q\nRun 'svc help' for usage.\n", cmd)
		os.Exit(1)
	}
}

// cmdInit scaffolds a services.yaml in the current directory.
func cmdInit(args []string) {
	outPath := "services.yaml"
	force := false

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--out", "-o":
			if i+1 >= len(args) {
				fatal("--out requires a path argument")
			}
			i++
			outPath = args[i]
		case "--force":
			force = true
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	if !force {
		if _, err := os.Stat(outPath); err == nil {
			fatalf("%s already exists — use --force to overwrite", outPath)
		}
	}

	if err := os.WriteFile(outPath, []byte(initTemplate), 0644); err != nil {
		fatalf("writing %s: %v", outPath, err)
	}

	fmt.Printf("Created %s\n", outPath)
	fmt.Println("Edit the file to describe your fleet, then run 'svc status'.")
}

// cmdStatus reads the manifest and polls all health endpoints.
func cmdStatus(args []string) {
	manifestPath := "services.yaml"
	filterTag := ""
	timeoutSec := 5

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--file", "-f":
			if i+1 >= len(args) {
				fatal("--file requires a path argument")
			}
			i++
			manifestPath = args[i]
		case "--tag":
			if i+1 >= len(args) {
				fatal("--tag requires a value")
			}
			i++
			filterTag = args[i]
		case "--timeout":
			if i+1 >= len(args) {
				fatal("--timeout requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &timeoutSec)
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	m, err := manifest.Load(manifestPath)
	if err != nil {
		fatal(err.Error())
	}

	if len(m.Services) == 0 {
		fmt.Println("No services defined in manifest.")
		return
	}

	// Build targets map, applying tag filter.
	targets := make(map[string]string)
	for id, svc := range m.Services {
		if filterTag != "" && !hasTag(svc.Tags, filterTag) {
			continue
		}
		targets[id] = manifest.ResolveHealthURL(m, svc)
	}

	if len(targets) == 0 {
		fmt.Printf("No services match tag %q.\n", filterTag)
		return
	}

	fmt.Printf("Checking %d service(s)...\n\n", len(targets))
	results := checker.CheckAllHealth(targets, timeoutSec)
	output.PrintStatusTable(os.Stdout, results)
}

func hasTag(tags []string, tag string) bool {
	for _, t := range tags {
		if t == tag {
			return true
		}
	}
	return false
}

// cmdCheck diffs the manifest against what's actually running.
func cmdCheck(args []string) {
	manifestPath := "services.yaml"
	noVersion := false
	noSystemd := false
	timeoutSec := 5

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--file", "-f":
			if i+1 >= len(args) {
				fatal("--file requires a path argument")
			}
			i++
			manifestPath = args[i]
		case "--no-version":
			noVersion = true
		case "--no-systemd":
			noSystemd = true
		case "--timeout":
			if i+1 >= len(args) {
				fatal("--timeout requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &timeoutSec)
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	m, err := manifest.Load(manifestPath)
	if err != nil {
		fatal(err.Error())
	}

	if len(m.Services) == 0 {
		fmt.Println("No services defined in manifest.")
		return
	}

	// Build ignore set from manifest.
	ignoreSet := make(map[string]bool)
	for _, u := range m.Meta.IgnoreUnits {
		ignoreSet[u] = true
	}
	// Also ignore units declared in the manifest itself.
	manifestUnits := make(map[string]bool)
	for _, svc := range m.Services {
		if svc.SystemdUnit != "" {
			manifestUnits[svc.SystemdUnit] = true
		}
	}

	// 1. Health checks.
	targets := make(map[string]string)
	for id, svc := range m.Services {
		targets[id] = manifest.ResolveHealthURL(m, svc)
	}
	healthResults := checker.CheckAllHealth(targets, timeoutSec)

	// 2. Systemd checks.
	systemdResults := make(map[string]checker.SystemdResult)
	useSystemd := !noSystemd && checker.SystemdAvailable()
	if useSystemd {
		for id, svc := range m.Services {
			if svc.SystemdUnit != "" {
				systemdResults[id] = checker.CheckUnit(svc.SystemdUnit)
			}
		}
	}

	// 3. Version checks (stub for now — will add in v0.2).
	_ = noVersion

	// 4. Undocumented units scan.
	var undocumented []string
	if useSystemd {
		operatorUnits, err := checker.ListOperatorUnits()
		if err == nil {
			for _, unit := range operatorUnits {
				if !manifestUnits[unit] && !ignoreSet[unit] {
					undocumented = append(undocumented, unit)
				}
			}
		}
	}

	// Print results.
	driftCount := output.PrintCheckTable(os.Stdout, healthResults, systemdResults, m.Services)

	if len(undocumented) > 0 {
		fmt.Println()
		fmt.Println("Undocumented units:")
		for _, u := range undocumented {
			fmt.Printf("  ⚠️  %s — active, no manifest entry\n", u)
		}
		driftCount += len(undocumented)
	}

	fmt.Println()
	if driftCount == 0 {
		fmt.Println("No drift detected. All services match the manifest.")
		os.Exit(0)
	}
	fmt.Printf("Summary: %d drift detected.\n", driftCount)
	os.Exit(1)
}

func printUsage() {
	fmt.Print(`svc — Service Manifest

Usage:
  svc init              scaffold a services.yaml in the current directory
  svc status            check live health for all services
  svc check             find drift between manifest and running system (coming soon)
  svc version           print version

Flags (status):
  --file, -f <path>     manifest file path (default: ./services.yaml)
  --tag <tag>           show only services with this tag
  --timeout <seconds>   health endpoint timeout (default: 5)

Flags (init):
  --out, -o <path>      output path (default: ./services.yaml)
  --force               overwrite existing file

`)
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, "Error:", msg)
	os.Exit(1)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "Error: "+format+"\n", args...)
	os.Exit(1)
}
