package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/ensignwesley/svc/internal/checker"
	"github.com/ensignwesley/svc/internal/manifest"
	"github.com/ensignwesley/svc/internal/output"
)

const version = "0.1.0"

const initTemplate = `# services.yaml — Service Manifest
# Generated by svc init. Edit to describe your fleet.
# Full schema reference: svc --help

manifest:
  version: 1
  host: localhost          # default health check host

services:

  # ── Example: minimal entry ────────────────────────────────────────────
  my-service:
    description: "One sentence describing what this service does."
    port: 8080

  # ── Example: fully specified entry ───────────────────────────────────
  # dead-drop:
  #   description: "Zero-knowledge burn-after-read secret sharing."
  #   port: 3001
  #   health_url: ""          # optional override; derived from port if absent
  #   systemd_unit: "dead-drop.service"
  #   repo: "ensignwesley/dead-drop"
  #   version: "1.1.0"
  #   max_major: 1            # ignore releases above this major version
  #   docs: "https://github.com/ensignwesley/dead-drop"
  #   tags: [security, http]
  #   added: "2026-03-15"
`

func main() {
	args := os.Args[1:]

	if len(args) == 0 || args[0] == "--help" || args[0] == "-h" {
		printHelp()
		os.Exit(0)
	}

	if args[0] == "--version" {
		fmt.Println("svc version", version)
		os.Exit(0)
	}

	cmd := args[0]
	rest := args[1:]

	switch cmd {
	case "init":
		runInit(rest)
	case "status":
		os.Exit(runStatus(rest))
	case "check":
		os.Exit(runCheck(rest))
	default:
		fmt.Fprintf(os.Stderr, "svc: unknown command %q\nRun 'svc --help' for usage.\n", cmd)
		os.Exit(1)
	}
}

// ── init ─────────────────────────────────────────────────────────────────────

func runInit(args []string) {
	outPath := "./services.yaml"
	force := false

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--out":
			if i+1 < len(args) {
				outPath = args[i+1]
				i++
			}
		case "--force":
			force = true
		}
	}

	if _, err := os.Stat(outPath); err == nil && !force {
		fmt.Fprintf(os.Stderr, "svc init: %s already exists. Use --force to overwrite.\n", outPath)
		os.Exit(1)
	}

	if err := os.WriteFile(outPath, []byte(initTemplate), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "svc init: cannot write %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Created %s\nEdit it to describe your fleet, then run: svc status\n", outPath)
}

// ── status ────────────────────────────────────────────────────────────────────

func runStatus(args []string) int {
	file := "./services.yaml"
	asJSON := false
	timeout := 5
	var filterTags []string

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--file", "-f":
			if i+1 < len(args) {
				file = args[i+1]
				i++
			}
		case "--json":
			asJSON = true
		case "--timeout":
			if i+1 < len(args) {
				fmt.Sscan(args[i+1], &timeout)
				i++
			}
		case "--tag":
			if i+1 < len(args) {
				filterTags = append(filterTags, args[i+1])
				i++
			}
		}
	}

	m, err := manifest.Load(file)
	if err != nil {
		fmt.Fprintln(os.Stderr, "svc status:", err)
		return 1
	}

	services := filterServices(m, filterTags)
	targets := make(map[string]string, len(services))
	for id, svc := range services {
		targets[id] = svc.ResolvedHealthURL(m.Meta.Host)
	}

	results := checker.CheckAll(targets, timeout)

	if asJSON {
		statuses := make([]output.ServiceStatus, 0, len(results))
		for _, r := range results {
			svc := services[r.ID]
			ss := output.ServiceStatus{
				ID:        r.ID,
				LatencyMs: r.LatencyMs,
			}
			if r.Up {
				ss.Status = "up"
			} else {
				ss.Status = "down"
			}
			if svc.Repo != "" && svc.Version != "" {
				vr := checker.CheckVersion(svc.Repo, svc.Version, svc.MaxMajor)
				ss.VersionCurrent = vr.Current
				ss.VersionLatest = vr.Latest
				ss.VersionStatus = vr.Status
			}
			statuses = append(statuses, ss)
		}
		out := output.StatusJSON{
			CheckedAt: output.Now(),
			Services:  statuses,
		}
		output.WriteJSON(os.Stdout, out)
		return 0
	}

	// Table output
	color := output.IsTTY()
	rows := make([]output.Row, 0, len(results))
	for _, r := range results {
		row := output.Row{ID: r.ID, LatencyMs: r.LatencyMs}
		if r.Up {
			row.Status = "up"
		} else {
			row.Status = "down"
		}
		svc := services[r.ID]
		if svc.Repo != "" && svc.Version != "" {
			vr := checker.CheckVersion(svc.Repo, svc.Version, svc.MaxMajor)
			switch vr.Status {
			case "behind":
				row.VersionStr = fmt.Sprintf("⚠ behind (latest: %s)", vr.Latest)
			case "current":
				row.VersionStr = "current"
			case "ahead":
				row.VersionStr = "ahead"
			}
		}
		rows = append(rows, row)
	}
	output.PrintTable(os.Stdout, rows, color)
	return 0
}

// ── check ─────────────────────────────────────────────────────────────────────

func runCheck(args []string) int {
	file := "./services.yaml"
	asJSON := false
	timeout := 5
	noVersion := false
	noSystemd := false
	var filterTags []string

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--file", "-f":
			if i+1 < len(args) {
				file = args[i+1]
				i++
			}
		case "--json":
			asJSON = true
		case "--timeout":
			if i+1 < len(args) {
				fmt.Sscan(args[i+1], &timeout)
				i++
			}
		case "--no-version":
			noVersion = true
		case "--no-systemd":
			noSystemd = true
		case "--tag":
			if i+1 < len(args) {
				filterTags = append(filterTags, args[i+1])
				i++
			}
		}
	}

	m, err := manifest.Load(file)
	if err != nil {
		fmt.Fprintln(os.Stderr, "svc check:", err)
		return 1
	}

	services := filterServices(m, filterTags)
	targets := make(map[string]string, len(services))
	for id, svc := range services {
		targets[id] = svc.ResolvedHealthURL(m.Meta.Host)
	}

	if !asJSON {
		fmt.Fprintf(os.Stdout, "Checking %d service(s)...\n\n", len(services))
	}

	healthResults := checker.CheckAll(targets, timeout)
	healthMap := make(map[string]checker.HealthResult, len(healthResults))
	for _, r := range healthResults {
		healthMap[r.ID] = r
	}

	var driftItems []output.DriftItem
	var jsonStatuses []output.ServiceStatus

	// Sort IDs for deterministic output
	ids := make([]string, 0, len(services))
	for id := range services {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	for _, id := range ids {
		svc := services[id]
		r := healthMap[id]

		js := output.ServiceStatus{
			ID:        id,
			LatencyMs: r.LatencyMs,
		}
		if r.Up {
			js.Status = "up"
		} else {
			js.Status = "down"
		}

		if !r.Up {
			errMsg := ""
			if r.Err != nil {
				errMsg = r.Err.Error()
			}
			driftItems = append(driftItems, output.DriftItem{
				ID:     id,
				Kind:   "down",
				Detail: errMsg,
			})
		}

		// Systemd check
		if !noSystemd && svc.SystemdUnit != "" {
			sr := checker.CheckSystemd(svc.SystemdUnit)
			active := sr.Active
			js.SystemdActive = &active
			if !sr.Active {
				driftItems = append(driftItems, output.DriftItem{
					ID:     id,
					Kind:   "unit-inactive",
					Detail: sr.Unit + " (" + sr.State + ")",
				})
			}
		}

		// Version check
		if !noVersion && svc.Repo != "" && svc.Version != "" {
			vr := checker.CheckVersion(svc.Repo, svc.Version, svc.MaxMajor)
			js.VersionCurrent = vr.Current
			js.VersionLatest = vr.Latest
			js.VersionStatus = vr.Status
			if vr.Status == "behind" {
				driftItems = append(driftItems, output.DriftItem{
					ID:     id,
					Kind:   "version-behind",
					Detail: fmt.Sprintf("running %s, latest %s", vr.Current, vr.Latest),
				})
			}
		}

		jsonStatuses = append(jsonStatuses, js)
	}

	// Undocumented unit scan
	var undocumented []string
	if !noSystemd {
		declaredUnits := make(map[string]bool)
		for _, svc := range services {
			if svc.SystemdUnit != "" {
				declaredUnits[svc.SystemdUnit] = true
			}
		}

		activeUnits, _ := checker.ListUserUnits()
		for _, u := range activeUnits {
			// Skip standard units
			if isSystemUnit(u) {
				continue
			}
			if !declaredUnits[u] {
				undocumented = append(undocumented, u)
			}
		}
	}

	exitCode := 0
	if len(driftItems) > 0 || len(undocumented) > 0 {
		exitCode = 1
	}

	if asJSON {
		out := output.CheckJSON{
			CheckedAt:    output.Now(),
			Services:     jsonStatuses,
			Undocumented: undocumented,
			DriftCount:   len(driftItems) + len(undocumented),
			ExitCode:     exitCode,
		}
		output.WriteJSON(os.Stdout, out)
		return exitCode
	}

	color := output.IsTTY()
	output.PrintDrift(os.Stdout, driftItems, undocumented, color)
	return exitCode
}

// ── helpers ───────────────────────────────────────────────────────────────────

func filterServices(m *manifest.Manifest, tags []string) map[string]manifest.Service {
	if len(tags) == 0 {
		return m.Services
	}
	filtered := make(map[string]manifest.Service)
	for id, svc := range m.Services {
		for _, ft := range tags {
			for _, t := range svc.Tags {
				if t == ft {
					filtered[id] = svc
					break
				}
			}
		}
	}
	return filtered
}

// isSystemUnit returns true for well-known systemd internal/platform units
// that shouldn't be flagged as undocumented.
func isSystemUnit(u string) bool {
	prefixes := []string{
		"dbus", "gpg-agent", "systemd-", "ssh-agent", "xdg-",
		"at-spi", "gvfs", "gnome-", "plasma-", "pipewire",
		"pulseaudio", "wireplumber", "dconf", "evolution-",
	}
	for _, p := range prefixes {
		if strings.HasPrefix(u, p) {
			return true
		}
	}
	return false
}

func printHelp() {
	fmt.Print(`svc — Service Manifest CLI

USAGE:
  svc <command> [flags]

COMMANDS:
  init      Scaffold a services.yaml in the current directory
  status    Poll all services and show a live health table
  check     Diff the manifest against what's actually running (exits 1 on drift)

GLOBAL FLAGS:
  --file, -f <path>    Manifest file (default: ./services.yaml)
  --version            Print version and exit
  --help, -h           Show this help

INIT FLAGS:
  --out <path>         Write to a different path (default: ./services.yaml)
  --force              Overwrite if file exists

STATUS FLAGS:
  --tag <tag>          Show only services with this tag (repeatable)
  --json               Machine-readable JSON output
  --timeout <sec>      Health check timeout (default: 5)

CHECK FLAGS:
  --tag <tag>          Check only services with this tag (repeatable)
  --no-version         Skip GitHub release checks
  --no-systemd         Skip systemd unit scanning
  --json               Machine-readable JSON output
  --timeout <sec>      Health check timeout (default: 5)

EXAMPLES:
  svc init                          Create services.yaml
  svc status                        Show live service health
  svc status --tag http             Show only HTTP-tagged services
  svc check                         Check for drift; exit 1 if any
  svc check --no-version            Skip version checks (faster)
  svc check --json | jq .           Machine-readable drift report
`)
}

// Ensure json is imported (used in runStatus --json path via WriteJSON)
var _ = json.Marshal
