package main

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/ensignwesley/svc/internal/adder"
	"github.com/ensignwesley/svc/internal/checker"
	"github.com/ensignwesley/svc/internal/manifest"
	"github.com/ensignwesley/svc/internal/output"
	"github.com/ensignwesley/svc/internal/watcher"
)

const version = "0.4.0"

const initTemplate = `# services.yaml — Service Manifest
# Generated by: svc init
#
# This file is the source of truth for your self-hosted fleet.
#
#   svc status   — check live health for every service
#   svc check    — find drift between this file and what's running
#   svc add <id>         — scaffold a new entry from a running service
#   svc add --scan       — probe all operator-installed systemd units at once
#

manifest:
  version: 1       # required; schema version (currently only 1 supported)
  host: localhost  # default host for health checks; override per-service via health_url

  # Units to ignore during undocumented-unit scan (svc check).
  # Use for system-managed services you deliberately exclude from the manifest.
  # ignore_units:
  #   - openclaw-gateway.service

services:

  # ── Fully specified example ──────────────────────────────────────────────────
  my-service:
    # What this service does. One sentence. Required (not enforced, but expected).
    description: "My service — describe it here"

    # Port the service listens on.
    # Derives health URL as http://{host}:{port}/health
    port: 8080

    # Override the health endpoint URL (optional).
    # Required when port is absent (e.g. static sites, external services).
    # health_url: "https://example.com/healthz"

    # systemd unit name — adds systemctl is-active check alongside HTTP poll.
    # systemd_unit: "my-service.service"

    # GitHub owner/repo for version drift detection.
    # repo: "owner/repo"

    # Currently deployed version (semver). Required for version drift detection.
    # version: "1.0.0"

    # Pin to a major version track (e.g. 22 for Node.js LTS).
    # max_major: 1

    # Link to docs or source.
    # docs: "https://github.com/owner/repo"

    # Tags for filtering: svc status --tag <tag>
    # tags:
    #   - http
    #   - security

    # Date this entry was added. Auto-set by 'svc add'.
    # added: "2026-03-16"

  # ── Minimal example (static site, no local port) ────────────────────────────
  # my-static-site:
  #   description: "Static site served by nginx"
  #   health_url: "https://example.com/"
`

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}

	cmd := os.Args[1]
	args := os.Args[2:]

	switch cmd {
	case "init":
		cmdInit(args)
	case "status":
		cmdStatus(args)
	case "check":
		cmdCheck(args)
	case "watch":
		cmdWatch(args)
	case "add":
		cmdAdd(args)
	case "version", "--version", "-v":
		fmt.Printf("svc version %s\n", version)
	case "help", "--help", "-h":
		printUsage()
	default:
		fmt.Fprintf(os.Stderr, "svc: unknown command %q\nRun 'svc help' for usage.\n", cmd)
		os.Exit(1)
	}
}

// cmdInit scaffolds a services.yaml in the current directory.
func cmdInit(args []string) {
	outPath := "services.yaml"
	force := false

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--out", "-o":
			if i+1 >= len(args) {
				fatal("--out requires a path argument")
			}
			i++
			outPath = args[i]
		case "--force":
			force = true
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	if !force {
		if _, err := os.Stat(outPath); err == nil {
			fatalf("%s already exists — use --force to overwrite", outPath)
		}
	}

	if err := os.WriteFile(outPath, []byte(initTemplate), 0644); err != nil {
		fatalf("writing %s: %v", outPath, err)
	}

	fmt.Printf("Created %s\n", outPath)
	fmt.Println("Edit the file to describe your fleet, then run 'svc status'.")
}

// cmdStatus reads the manifest and polls all health endpoints.
func cmdStatus(args []string) {
	manifestPath := "services.yaml"
	filterTag := ""
	timeoutSec := 5
	jsonOut := false

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--file", "-f":
			if i+1 >= len(args) {
				fatal("--file requires a path argument")
			}
			i++
			manifestPath = args[i]
		case "--tag":
			if i+1 >= len(args) {
				fatal("--tag requires a value")
			}
			i++
			filterTag = args[i]
		case "--timeout":
			if i+1 >= len(args) {
				fatal("--timeout requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &timeoutSec)
		case "--json":
			jsonOut = true
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	m, err := manifest.Load(manifestPath)
	if err != nil {
		fatal(err.Error())
	}

	if len(m.Services) == 0 {
		fmt.Println("No services defined in manifest.")
		return
	}

	// Build targets map, applying tag filter.
	targets := make(map[string]string)
	for id, svc := range m.Services {
		if filterTag != "" && !hasTag(svc.Tags, filterTag) {
			continue
		}
		targets[id] = manifest.ResolveHealthURL(m, svc)
	}

	if len(targets) == 0 {
		fmt.Printf("No services match tag %q.\n", filterTag)
		return
	}

	results := checker.CheckAllHealth(targets, timeoutSec)

	if jsonOut {
		statuses := make([]output.ServiceStatus, 0, len(results))
		for _, r := range results {
			status := "down"
			if r.Up {
				status = "up"
			}
			statuses = append(statuses, output.ServiceStatus{
				ID:        r.ServiceID,
				Status:    status,
				LatencyMs: r.LatencyMS,
			})
		}
		out := output.StatusJSON{
			CheckedAt: output.Now(),
			Services:  statuses,
		}
		if err := output.WriteJSON(os.Stdout, out); err != nil {
			fatalf("json output: %v", err)
		}
		return
	}

	fmt.Printf("Checking %d service(s)...\n\n", len(targets))
	output.PrintStatusTable(os.Stdout, results)
}

func hasTag(tags []string, tag string) bool {
	for _, t := range tags {
		if t == tag {
			return true
		}
	}
	return false
}

// cmdAdd probes a running service and scaffolds a manifest entry to stdout.
func cmdAdd(args []string) {
	// Handle --scan mode first (no positional id required).
	for _, arg := range args {
		if arg == "--scan" {
			cmdAddScan(args)
			return
		}
	}

	if len(args) == 0 || strings.HasPrefix(args[0], "--") {
		fatal("svc add requires a service id\nUsage: svc add <id> [--port <n>] [--write]\n       svc add --scan [--write] [--include-known]")
	}

	id := args[0]
	portHint := 0
	write := false
	manifestPath := "services.yaml"
	timeoutSec := 5

	for i := 1; i < len(args); i++ {
		switch args[i] {
		case "--port", "-p":
			if i+1 >= len(args) {
				fatal("--port requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &portHint)
		case "--write":
			write = true
		case "--file", "-f":
			if i+1 >= len(args) {
				fatal("--file requires a path argument")
			}
			i++
			manifestPath = args[i]
		case "--timeout":
			if i+1 >= len(args) {
				fatal("--timeout requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &timeoutSec)
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	fmt.Fprintf(os.Stderr, "Probing %q...\n", id)
	result := adder.Probe(id, portHint, timeoutSec)

	today := time.Now().UTC().Format("2006-01-02")

	yaml := adder.Scaffold(result, today)

	if !write {
		fmt.Println("# Add the following to your services.yaml:")
		fmt.Println()
		fmt.Print(yaml)
		fmt.Println()
		fmt.Fprintf(os.Stderr, "Review the entry, then run: svc add %s --write\n", id)
		return
	}

	// --write: append to manifest file.
	f, err := os.OpenFile(manifestPath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		fatalf("opening %s: %v", manifestPath, err)
	}
	defer f.Close()
	if _, err := fmt.Fprint(f, "\n"+yaml); err != nil {
		fatalf("writing to %s: %v", manifestPath, err)
	}
	fmt.Fprintf(os.Stderr, "Added %q to %s\n", id, manifestPath)
}

// cmdAddScan discovers all operator-installed systemd units and scaffolds
// manifest entries for any not already documented.
func cmdAddScan(args []string) {
	write := false
	includeKnown := false
	manifestPath := "services.yaml"
	timeoutSec := 5

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--scan":
			// already handled — skip
		case "--write":
			write = true
		case "--include-known":
			includeKnown = true
		case "--file", "-f":
			if i+1 >= len(args) {
				fatal("--file requires a path argument")
			}
			i++
			manifestPath = args[i]
		case "--timeout":
			if i+1 >= len(args) {
				fatal("--timeout requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &timeoutSec)
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	// Load existing manifest to build known-ID set.
	knownIDs := make(map[string]bool)
	if m, err := manifest.Load(manifestPath); err == nil {
		for id := range m.Services {
			knownIDs[id] = true
		}
	}

	fmt.Fprintln(os.Stderr, "Scanning operator-installed systemd units...")
	results, err := adder.ScanFleet(knownIDs, timeoutSec)
	if err != nil {
		fatalf("scan failed: %v", err)
	}

	if len(results) == 0 {
		fmt.Fprintln(os.Stderr, "No operator-installed units found.")
		return
	}

	today := time.Now().UTC().Format("2006-01-02")

	var toWrite []adder.ScanResult
	for _, r := range results {
		if r.AlreadyInManifest && !includeKnown {
			fmt.Fprintf(os.Stderr, "  skip  %s (already in manifest)\n", r.ID)
			continue
		}
		toWrite = append(toWrite, r)
	}

	if len(toWrite) == 0 {
		fmt.Fprintln(os.Stderr, "All discovered units are already in the manifest.")
		fmt.Fprintln(os.Stderr, "Use --include-known to scaffold entries for existing services too.")
		return
	}

	// Build combined scaffold output.
	var combined strings.Builder
	for _, r := range toWrite {
		label := ""
		if r.AlreadyInManifest {
			label = " (already documented)"
		}
		fmt.Fprintf(os.Stderr, "  probe %s%s\n", r.ID, label)
		combined.WriteString(adder.Scaffold(r.ProbeResult, today))
	}

	if !write {
		fmt.Printf("# svc add --scan — %d unit(s) found, %d new\n", len(results), len(toWrite))
		fmt.Printf("# Add the following to your services.yaml:\n\n")
		fmt.Print(combined.String())
		fmt.Fprintf(os.Stderr, "\nReview the entries, then run: svc add --scan --write\n")
		return
	}

	// --write: append all new entries to manifest.
	f, err := os.OpenFile(manifestPath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		fatalf("opening %s: %v", manifestPath, err)
	}
	defer f.Close()
	if _, err := fmt.Fprint(f, "\n"+combined.String()); err != nil {
		fatalf("writing to %s: %v", manifestPath, err)
	}
	fmt.Fprintf(os.Stderr, "Added %d service(s) to %s\n", len(toWrite), manifestPath)
}

// cmdWatch runs the continuous polling loop with state-change alerting.
func cmdWatch(args []string) {
	cfg := watcher.Config{
		ManifestPath:    "services.yaml",
		StatePath:       watcher.DefaultStatePath(),
		DeliveryLogPath: watcher.DefaultDeliveryFailurePath(),
		Interval:        60,
		FailThreshold:   2,
		TimeoutSec:      5,
	}

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--file", "-f":
			if i+1 >= len(args) {
				fatal("--file requires a path argument")
			}
			i++
			cfg.ManifestPath = args[i]
		case "--webhook":
			if i+1 >= len(args) {
				fatal("--webhook requires a URL")
			}
			i++
			cfg.WebhookURL = args[i]
		case "--interval":
			if i+1 >= len(args) {
				fatal("--interval requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &cfg.Interval)
		case "--failures":
			if i+1 >= len(args) {
				fatal("--failures requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &cfg.FailThreshold)
		case "--state":
			if i+1 >= len(args) {
				fatal("--state requires a path")
			}
			i++
			cfg.StatePath = args[i]
		case "--timeout":
			if i+1 >= len(args) {
				fatal("--timeout requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &cfg.TimeoutSec)
		case "--no-systemd":
			cfg.NoSystemd = true
		case "--stdout":
			cfg.Stdout = true
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	if err := watcher.Watch(cfg, os.Stdout); err != nil {
		fatal(err.Error())
	}
}

// cmdCheck diffs the manifest against what's actually running.
func cmdCheck(args []string) {
	manifestPath := "services.yaml"
	noVersion := false
	noSystemd := false
	timeoutSec := 5
	jsonOut := false

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--file", "-f":
			if i+1 >= len(args) {
				fatal("--file requires a path argument")
			}
			i++
			manifestPath = args[i]
		case "--no-version":
			noVersion = true
		case "--no-systemd":
			noSystemd = true
		case "--timeout":
			if i+1 >= len(args) {
				fatal("--timeout requires a value")
			}
			i++
			fmt.Sscanf(args[i], "%d", &timeoutSec)
		case "--json":
			jsonOut = true
		default:
			fatalf("unknown flag: %s", args[i])
		}
	}

	m, err := manifest.Load(manifestPath)
	if err != nil {
		fatal(err.Error())
	}

	if len(m.Services) == 0 {
		fmt.Println("No services defined in manifest.")
		return
	}

	// Build ignore set from manifest.
	ignoreSet := make(map[string]bool)
	for _, u := range m.Meta.IgnoreUnits {
		ignoreSet[u] = true
	}
	// Also ignore units declared in the manifest itself.
	manifestUnits := make(map[string]bool)
	for _, svc := range m.Services {
		if svc.SystemdUnit != "" {
			manifestUnits[svc.SystemdUnit] = true
		}
	}

	// 1. Health checks.
	targets := make(map[string]string)
	for id, svc := range m.Services {
		targets[id] = manifest.ResolveHealthURL(m, svc)
	}
	healthResults := checker.CheckAllHealth(targets, timeoutSec)

	// 2. Systemd checks.
	systemdResults := make(map[string]checker.SystemdResult)
	useSystemd := !noSystemd && checker.SystemdAvailable()
	if useSystemd {
		for id, svc := range m.Services {
			if svc.SystemdUnit != "" {
				systemdResults[id] = checker.CheckUnit(svc.SystemdUnit)
			}
		}
	}

	// 3. Version checks (stub for now — will add in v0.2).
	_ = noVersion

	// 4. Undocumented units scan.
	var undocumented []string
	if useSystemd {
		operatorUnits, err := checker.ListOperatorUnits()
		if err == nil {
			for _, unit := range operatorUnits {
				if !manifestUnits[unit] && !ignoreSet[unit] {
					undocumented = append(undocumented, unit)
				}
			}
		}
	}

	if jsonOut {
		statuses := make([]output.ServiceStatus, 0, len(healthResults))
		for _, r := range healthResults {
			status := "down"
			if r.Up {
				status = "up"
			}
			ss := output.ServiceStatus{
				ID:        r.ServiceID,
				Status:    status,
				LatencyMs: r.LatencyMS,
			}
			if sr, ok := systemdResults[r.ServiceID]; ok {
				active := sr.Active
				ss.SystemdActive = &active
			}
			statuses = append(statuses, ss)
		}
		// Calculate drift for JSON output.
		driftJSON := 0
		for _, r := range healthResults {
			if !r.Up {
				driftJSON++
			}
		}
		for _, sr := range systemdResults {
			if !sr.Active {
				driftJSON++
			}
		}
		driftJSON += len(undocumented)
		exitCode := 0
		if driftJSON > 0 {
			exitCode = 1
		}
		out := output.CheckJSON{
			CheckedAt:    output.Now(),
			Services:     statuses,
			Undocumented: undocumented,
			DriftCount:   driftJSON,
			ExitCode:     exitCode,
		}
		if err := output.WriteJSON(os.Stdout, out); err != nil {
			fatalf("json output: %v", err)
		}
		os.Exit(exitCode)
	}

	// Print results.
	driftCount := output.PrintCheckTable(os.Stdout, healthResults, systemdResults, m.Services)

	if len(undocumented) > 0 {
		fmt.Println()
		fmt.Println("Undocumented units:")
		for _, u := range undocumented {
			fmt.Printf("  ⚠️  %s — active, no manifest entry\n", u)
		}
		driftCount += len(undocumented)
	}

	fmt.Println()
	if driftCount == 0 {
		fmt.Println("No drift detected. All services match the manifest.")
		os.Exit(0)
	}
	fmt.Printf("Summary: %d drift detected.\n", driftCount)
	os.Exit(1)
}

func printUsage() {
	fmt.Print(`svc — Service Manifest

Usage:
  svc init              scaffold a services.yaml in the current directory
  svc status            check live health for all services
  svc check             find drift between manifest and running system
  svc add <id>          probe a running service and scaffold a manifest entry
  svc add --scan        probe all operator-installed systemd units at once
  svc watch             continuously poll the fleet and alert on state changes
  svc version           print version

Flags (status, check):
  --file, -f <path>     manifest file path (default: ./services.yaml)
  --timeout <seconds>   health endpoint timeout (default: 5)
  --json                machine-readable JSON output

Flags (status):
  --tag <tag>           show only services with this tag

Flags (check):
  --no-systemd          skip systemd unit checks
  --no-version          skip version drift checks

Flags (init):
  --out, -o <path>      output path (default: ./services.yaml)
  --force               overwrite existing file

Flags (add):
  --port, -p <n>        port hint for health probe
  --write               append scaffolded entry to services.yaml
  --file, -f <path>     manifest file path (default: ./services.yaml)

Flags (add --scan):
  --write               append all new entries to services.yaml
  --include-known       include services already in the manifest
  --file, -f <path>     manifest file path (default: ./services.yaml)

Flags (watch):
  --webhook <url>       webhook URL for state-change alerts
  --interval <seconds>  poll interval (default: 60)
  --failures <n>        consecutive failures before DOWN alert (default: 2)

`)
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, "Error:", msg)
	os.Exit(1)
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "Error: "+format+"\n", args...)
	os.Exit(1)
}
